repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-ast
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
